// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:e17b1206-41bb-4221-bbfe-8a3378ae16f8",
    "aws_cognito_region": "eu-west-1",
    "oauth": {},
    "aws_mobile_analytics_app_id": "fae7d0d4b10646a78691c05c0778d084",
    "aws_mobile_analytics_app_region": "eu-west-1"
};


export default awsmobile;
